node:
  port: 5000
  node_id: "localhost"

transfer:
  chunk_size: 1150
  window_size: 64
  base_rto_ms: 50
  ttl_sec: 300
  max_rto_ms: 5000

fec:
  enabled: false
  k: 4
  r: 2

custody:
  max_retries: 10
  backoff_base_sec: 2